In [1]:
import numpy as np
a = np.random.randn(4, 3) 
b = np.random.randn(3, 2)

In [2]:
a.shape

(4, 3)

In [3]:
b.shape

(3, 2)

In [4]:
a

array([[ 2.84301588, -0.87595451, -1.59909475],
       [ 0.8243915 ,  1.19342116, -1.26316979],
       [-1.42486466,  0.69686727, -0.38416373],
       [ 2.05516198,  0.5495833 ,  1.37204306]])

In [5]:
b

array([[-0.12543347,  0.43638536],
       [ 1.87422695, -0.69095175],
       [-0.4847763 ,  1.38152071]])

In [6]:
c=a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [7]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) 

In [8]:
c = np.dot(a,b)

In [9]:
c.shape

(12288, 45)

In [10]:
a

array([[ 7.58177981e-01,  2.83401675e+00, -1.23196815e+00, ...,
        -1.48382863e-01, -2.04887735e-01,  5.50688321e-01],
       [ 9.63779315e-01,  3.84510170e-01,  7.80019549e-01, ...,
         5.80620426e-01,  7.51218372e-01, -1.62128588e-01],
       [ 7.17156022e-01, -1.91175179e+00,  7.50703566e-01, ...,
         1.68906792e+00,  3.65244104e-01,  9.31245341e-02],
       ...,
       [ 6.60433408e-01,  2.58037707e-01,  5.10666226e-02, ...,
        -4.02103610e-01, -1.19371509e-01, -7.04870033e-01],
       [ 4.10307883e-01, -8.80616962e-01,  2.00868815e+00, ...,
         8.25796106e-01,  1.34557007e+00,  2.92649502e-01],
       [ 1.01745802e+00, -1.76968336e+00, -4.45240930e-01, ...,
         4.14388109e-04,  7.15837795e-01, -9.43963096e-01]])

In [11]:
b

array([[ 1.66341882, -0.47399709, -0.01334167, ...,  0.30096778,
        -0.74926246, -0.04005266],
       [-0.20163442,  0.86075433, -0.3799763 , ...,  1.24137558,
         0.4201037 ,  0.22980802],
       [-0.98506856,  0.94087808, -0.4401994 , ...,  1.88749865,
         0.86477764,  1.0573208 ],
       ...,
       [ 0.28100955,  0.28775724,  0.23675838, ..., -0.49810428,
        -1.05339811, -0.46356337],
       [-0.04270933,  1.13897169, -0.65776336, ...,  0.31010277,
         1.50933355, -1.21556672],
       [-1.87931596,  0.35567077,  0.47761719, ...,  0.45802371,
         0.15410568,  0.45237837]])

In [12]:
c

array([[ 1.33753862e+01,  4.48849954e+00, -1.15559243e+01, ...,
        -3.62316469e+00,  1.21248706e+01, -3.01030204e+00],
       [-1.01797173e+01,  4.91952510e+00, -2.18603865e+00, ...,
        -8.85499810e+00,  2.19926967e+01,  5.16267893e+00],
       [ 2.54541794e+00,  2.96124263e+00,  7.82192353e+00, ...,
         1.60243662e+01,  1.79667153e+01,  2.50600949e+01],
       ...,
       [ 2.51940072e+00, -5.03279735e-01, -1.13921528e+01, ...,
         1.12742674e+01, -1.99102733e+00, -3.36924841e+00],
       [-1.41394262e+01,  7.11954008e+00, -5.66437175e+00, ...,
        -5.47664550e+00, -1.86695487e-02,  8.08963256e+00],
       [-1.71941811e+01, -2.72106497e+01,  8.76601747e+00, ...,
         2.52852252e+00, -1.03578882e+01, -7.92487679e+00]])

In [13]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [14]:
a

array([[-0.31151432,  0.81088568,  0.76918547],
       [ 1.6493233 ,  0.04784519,  1.5716824 ],
       [-1.50440337,  0.10900576,  0.23165012]])

In [15]:
b

array([[ 0.18841515],
       [-1.76559666],
       [-0.39939212]])

In [16]:
c

array([[-0.05869402,  0.15278315,  0.1449262 ],
       [-2.91203972, -0.08447531, -2.7749572 ],
       [ 0.60084685, -0.04353604, -0.09251923]])

In [17]:
-0.31151432* 0.18841515

-0.058694017329948

In [18]:
0.81088568* 0.18841515

0.15278314703005202

In [19]:
1.6493233*-1.76559666

-2.912039709740178

In [20]:
a = np.random.randn(3, 4)
b=np.random.randn(4,1)

In [21]:
a

array([[-2.36815198, -0.80874456, -0.81781898,  0.85051386],
       [-0.66339353, -0.28502204, -0.66638649,  1.261227  ],
       [-0.57965237, -0.33747807,  0.48821983, -0.59942561]])

In [22]:
b

array([[-1.19409882],
       [ 1.59337942],
       [ 0.44127343],
       [ 1.34745295]])

In [23]:
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [24]:
c=b+a.T

In [25]:
c

array([[-3.5622508 , -1.85749235, -1.7737512 ],
       [ 0.78463486,  1.30835738,  1.25590135],
       [-0.37654555, -0.22511306,  0.92949326],
       [ 2.1979668 ,  2.60867994,  0.74802734]])

In [26]:
-2.36815198 + -1.19409882

-3.5622508

In [27]:
0.85051386 + 1.34745295

2.19796681

In [30]:
a= range(3)

In [31]:
a

range(0, 3)

In [32]:
a[0]

0

In [33]:
a[2]

2

In [34]:
a[3]

IndexError: range object index out of range

In [35]:
b

array([[-1.19409882],
       [ 1.59337942],
       [ 0.44127343],
       [ 1.34745295]])

In [36]:
b[1]

array([1.59337942])

In [37]:
b[1][0]

1.5933794184801489

In [38]:
b[1][1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [39]:
c = a + b.T

ValueError: operands could not be broadcast together with shapes (3,) (1,4) 

In [40]:
c = a+b

In [41]:
c

array([[-1.19409882, -0.19409882,  0.80590118],
       [ 1.59337942,  2.59337942,  3.59337942],
       [ 0.44127343,  1.44127343,  2.44127343],
       [ 1.34745295,  2.34745295,  3.34745295]])

In [43]:
a=np.random.randint(10,size=(3,4))

In [44]:
a

array([[9, 9, 8, 1],
       [2, 2, 2, 8],
       [6, 5, 3, 5]])

In [46]:
b=np.random.randint(10,size=(4,1))

In [47]:
b

array([[3],
       [9],
       [4],
       [9]])

In [48]:
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [49]:
c=a+b

ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 

In [51]:
a.shape

(3, 4)

In [52]:
b.shape

(4, 1)

In [53]:
c=a.T+b

In [54]:
c

array([[12,  5,  9],
       [18, 11, 14],
       [12,  6,  7],
       [10, 17, 14]])

In [55]:
a.T

array([[9, 2, 6],
       [9, 2, 5],
       [8, 2, 3],
       [1, 8, 5]])

In [56]:
b

array([[3],
       [9],
       [4],
       [9]])

In [63]:
for i in range(3):
  for j in range(4):
    print (a[i][j] + b[j])

[12]
[18]
[12]
[10]
[5]
[11]
[6]
[17]
[9]
[14]
[7]
[14]


In [64]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [65]:
c


array([[ 0.68227971,  0.82746435,  0.6193262 ],
       [-0.1043026 ,  0.49526474, -0.14735557]])

In [66]:
c.shape

(2, 3)

In [67]:
a

array([[ 0.15452202,  0.29970666,  0.09156851],
       [-0.35053485,  0.2490325 , -0.39358782]])

In [71]:
a=np.random.randint(5,size=(3,4))

In [72]:
a

array([[2, 3, 4, 0],
       [4, 0, 0, 3],
       [1, 0, 1, 4]])

In [74]:
b=np.random.randint(5,size=(4,1))

In [75]:
b

array([[4],
       [0],
       [4],
       [2]])

In [77]:
a.shape

(3, 4)

In [78]:
b.shape

(4, 1)

In [80]:
for i in range(3):
  for j in range(4):
    print( a[i][j] + b[j])

[6]
[3]
[8]
[2]
[8]
[0]
[4]
[5]
[5]
[0]
[5]
[6]


In [81]:
print(a+b.T)

[[6 3 8 2]
 [8 0 4 5]
 [5 0 5 6]]


In [82]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [83]:
c=np.dot(a,b)

In [84]:
c

array([[-1.15070676, -0.30357459],
       [-0.83337896,  1.72470386],
       [ 0.06832268, -0.37350359],
       [ 0.53437217, -2.49393532]])

In [85]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])


In [86]:
image.shape

(3, 3, 2)

In [90]:
image.shape[0]

3