In [4]:
import numpy as np
x = np.arange(4)
print("x = " + str(x) + "x.shape = " + str(x.shape))
xx= x.reshape(4,1)
print("xx = " + str(x) + "xx.shape = " + str(xx.shape))
y = np.ones(5)
print("y = " + str(y) + "y.shape = " + str(y.shape))
z = xx+y
print("z(xx+y) = " + str(z) + "z.shape = " + str(z.shape))

x = [0 1 2 3]x.shape = (4,)
xx = [0 1 2 3]xx.shape = (4, 1)
y = [1. 1. 1. 1. 1.]y.shape = (5,)
z(xx+y) = [[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]z.shape = (4, 5)


In [7]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print ("B = " + str(B) + ", B.Shape() = " + str(B.shape))

B = [[-1.50732273]
 [-0.95104126]
 [-2.01843685]
 [-0.350199  ]], B.Shape() = (4, 1)


In [8]:
A

array([[-1.58407935, -1.00575931,  1.08251593],
       [-1.26003416,  0.34850907, -0.03951617],
       [-0.50190371, -0.82170597, -0.69482717],
       [-0.4883654 ,  0.18676215, -0.04859575]])